require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/spends', type: :request do
  before :each do
    @user = User.create(name: 'Samantha Woods', email: 'sam@outlook.com', password: 'password',
                        password_confirmation: 'password')
    @group = Group.create(name: 'Pets', icon: 'pet_img', user: @user)
    @spend = Spend.create(name: 'Food', amount: 20, author: @user)
    @spend.groups << @group
    sign_in @user
  end

  describe 'GET /index' do
    it 'returns http success' do
      get group_spends_path(@group)
      expect(response).to have_http_status(302)
    end
  end

  describe 'GET /show' do
    it 'returns http success' do
      get group_spends_path(@group, @spend)
      expect(response).to have_http_status(302)
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_group_spend_path(@group)
      expect(response).to have_http_status(302)
    end
  end
end
